### ISSUE TITLE
Is this a hoax?

### ISSUE THREAD

**Issue by SteveFirsake** [kartoza/leaflet-wms-legend#4]
Seems like you just did a nice image and plenty of HTML and CSS...

If it is true, i will provide you with a link to use so that you can prove your results. Nice concept though...although this is a hoax...seen your code, you only use an image of the legend and use CSS to display it!!!

**Comment by timlinux** [comment]
@SteveFirsake do you have an actual question or query? I encourage you to read the README for usage. This is not a hoax - its just a small plugin for Leaflet. Creating a small core application which is extended by small plugins is a design choice for leaflet and our implementation for the WMS legend widget is consistent with that approach. 

The actual implementation logic can be found in https://github.com/kartoza/leaflet-wms-legend/blob/master/leaflet.wmslegend.js which (combined with the css) will fetch the legend by doing a getLegendGraphic WMS request and then display the result in an inset box in your map.

I'm closing this issue since you have not actually reported a bug.

**Comment by SteveFirsake** [comment]
There were no results at all, and the legend displayed on that link was an
image, i.e. not pulled directly from source. I found a different library
that implements the getLegendGraphic more simpler.

Regards,


Steve

**Comment by timlinux** [comment]
Hi

This part will call getLegendGraphic on the WMS service:

```
uri = "http://maps.kartoza.com/cgi-bin/qgis_mapserv.fcgi?";
uri += "map=/web/Boosmansbos/Boosmansbos.qgs&";
uri += "&SERVICE=WMS&VERSION=1.3.0&SLD_VERSION=1.1.0&";
uri += "REQUEST=GetLegendGraphic&FORMAT=image/jpeg&LAYER=Boosmansbos&STYLE=";
L.wmsLegend(uri);
```

and then place it in the legend. The legend fetched is not a static image, but one generated at run time based on the layers available in the map. Anyway I am glad you found something more suited to your needs...

Regards

Tim

**Comment by SteveFirsake** [comment]
I understand now, I realised that saving the sample directly only takes an
image of the legend. Sorry. Your code now works effectively

**Comment by timlinux** [comment]
Great to hear it @SteveFirsake !
